plugins:
  - extension: .ts
    install_command: npm i --location=global @commentcov/commentcov-plugin-typescript
    execute_command: npx commentcov-plugin-typescript
target_path: .
exclude_paths:
  - ./build/**/**
  - ./docs/**/**
  - ./node_modules/**/**
  - ./src/generated/**/**
mode: file_scope
